version: "3"

services:

  squiddb:
    image: postgres:12
    container_name: squiddb
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT}:5432"
      # - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]
