version: '3'

services:
  squid-db:
    image: postgres:12
    container_name: squid-db
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_PASSWORD: postgres
    ports:
      - '0.0.0.0:${DB_PORT}:5432' # needed by the processor running as nodejs process (w-out docker)
    command: ['postgres', '-c', 'log_statement=all']

networks:
  default:
    external:
      name: node-network
