version: "3"

services:

  archive-db:
    container_name: archive-db
    image: postgres:12  # CockroachDB cluster might be a better fit for production deployment
    restart: always
    network_mode: host
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: squid-archive

  archive-ingest:
    container_name: archive-ingest
    depends_on:
      - archive-db
    restart: on-failure
    image: subsquid/substrate-ingest:firesquid
    network_mode: host
    command: [
       # smartnet node endpoint
       "-e", "ws://127.0.0.1:9943",
       "--out", "postgres://postgres:postgres@127.0.0.1:5432/squid-archive"
    ]
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0

  # localhost:8000
  archive-gateway:
    image: subsquid/substrate-gateway:firesquid
    container_name: archive-gateway
    depends_on:
      - archive-db
    network_mode: host
    environment:
      RUST_LOG: "substrate_gateway=info,actix_server=info"
    command: [
       "--database-url", "postgres://postgres:postgres@127.0.0.1:5432/squid-archive",
       "--database-max-connections", "3", # max number of concurrent database connections
       "--contracts-support"
    ]

  # optional
  # localhost:3000/graphql
  # archive-explorer:
  #   image: subsquid/substrate-explorer:firesquid
  #   container_name: archive-explorer
  #   network_mode: host
  #   environment:
  #     DB_TYPE: postgres # set to `cockroach` for Cockroach DB
  #     DB_HOST: "127.0.0.1"
  #     DB_PORT: "5432"
  #     DB_NAME: "squid-archive"
  #     DB_USER: "postgres"
  #     DB_PASS: "postgres"
