name: Deploy docker image to devnet

inputs:
  registry:
    description: Registry name, either squid-processor or squid-api
    required: true
  image_tag:
    description: Tag of the docker image to be deployed
    required: true
  autocommit-gpg-key-b64:
    description: base64 encoded signing key
    required: true
  autocommit-gpg-key-fingerprint:
    description: fingerprint of gpg key
    required: true
  autocommit-author:
    description: Commit author
    required: true
  aws_devnet_access_key_id:
    required: true
  aws_devnet_secret_access_key:
    required: true
  github_token:
    required: true
  kustomize_version:
    required: false
    default: "5.1.1"

runs:
  using: composite
  steps:
    - name: Check if registry input is valid
      if: ${{ inputs.registry != 'squid-processor' && inputs.registry != 'squid-api' }}
      shell: bash
      run: |
        echo "Invalid registry input"
        exit 1

    - name: GIT | Get branch info & current commit sha.
      id: get_branch
      shell: bash
      run: |
        echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: GIT | Checkout aleph-apps repo
      uses: actions/checkout@v4
      with:
        repository: Cardinal-Cryptography/aleph-apps
        token: ${{ inputs.github_token }}
        path: "aleph-apps"
        ref: main
    
    - name: KUSTOMIZE | Init kustomize
      uses: imranismail/setup-kustomize@v2
      with:
        kustomize-version: ${{ inputs.kustomize_version }}

    - name: KUSTOMIZE | Update docker image tag for squid
      shell: bash
      env:
        DEPLOY_IMAGE: public.ecr.aws/p6e8q1z1/${{ inputs.registry }}:${{ inputs.image_tag }}
      run: |
        cd aleph-apps/indexer/squid/overlays/devnet/eu-central-1
        kustomize edit set image "${{ inputs.registry }}-image-placeholder=${{ env.DEPLOY_IMAGE }}"

    - name: Configure signing key
      shell: bash
      run: |
        echo ${{ inputs.autocommit-gpg-key-b64 }} | base64 -d > key.gpg
        gpg --import key.gpg
        rm key.gpg
        git config --global user.signingkey $(echo ${{ inputs.autocommit-gpg-key-fingerprint }} | tail -c 17)

    - name: GIT | Commit changes to aleph-apps repository
      uses: EndBug/add-and-commit@v5.1.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        author_name: ${{ inputs.autocommit-author }}
        author_email: ${{ inputs.autocommit-email }}
        commit: -S
        message: 'Updating Indexer ${{ inputs.registry }} docker image tag: ${{ inputs.image_tag }}'
        add: '*.yaml'
        cwd: 'aleph-apps'
        branch: main
