name: Deploy docker image to devnet

inputs:
  registry:
    description: Registry name, either squid-processor or squid-api
    required: true
  aws_devnet_access_key_id:
    required: true
  aws_devnet_secret_access_key:
    required: true
  ci_s3bucket_name:
    required: true
  github_token:
    required: true

runs:
  using: composite
  steps:
    - name: Check if registry input is valid
      if: ${{ inputs.registry != 'squid-processor' && inputs.registry != 'squid-api' }}
      shell: bash
      run: |
        echo "Invalid registry input"
        exit 1

    - name: GIT | Get branch info & current commit sha.
      id: get_branch
      shell: bash
      run: |
        echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: GIT | Checkout aleph-apps repo
      uses: actions/checkout@master
      with:
        repository: Cardinal-Cryptography/aleph-apps
        token: ${{ inputs.github_token }}
        path: "aleph-apps"
        ref: A0-1459-indexer
    
    - name: KUSTOMIZE | Init kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: '3.8.6'

    - name: KUSTOMIZE | Update docker image tag
      shell: bash
      env:
        DEPLOY_IMAGE: public.ecr.aws/p6e8q1z1/${{ inputs.registry }}:${{ steps.get_branch.outputs.sha_short }}
      run: |
        cd aleph-apps/indexer/squid/overlays/devnet/eu-central-1
        kustomize edit set image "${{ inputs.registry }}-image-placeholder=${{ env.DEPLOY_IMAGE }}"

    - name: GIT | Commit changes to aleph-apps repository
      uses: EndBug/add-and-commit@v5.1.0
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        author_name: AlephZero Automation
        author_email: alephzero@10clouds.com
        message: 'Updating Indexer ${{ inputs.registry }} docker image tag: ${{ steps.get_branch.outputs.branch }}'
        add: '*.yaml'
        cwd: 'aleph-apps'
        branch: A0-1459-indexer
