name: Build and push docker image

inputs:
  registry:
    description: Registry name, either squid-processor or squid-api
    required: true
  target:
    description: --target argument for docker build command
    required: true
  download_featurenet_addresses:
    description: If 'true', an additional image with metadata from fe-benjamin will be built
  aws_mainnet_access_key_id:
    required: true
  aws_mainnet_secret_access_key:
    required: true
  aws_devnet_access_key_id:
    required: true
  aws_devnet_secret_access_key:
    required: true
  ci_s3bucket_name:
    required: true

outputs:
  image:
    description: Image URL
    value: ${{ steps.outputs.outputs.image }}

runs:
  using: composite
  steps:
    - name: Check if registry input is valid
      if: ${{ inputs.registry != 'squid-processor' && inputs.registry != 'squid-api' }}
      shell: bash
      run: |
        echo "Invalid registry input"
        exit 1

    - name: GIT | Get branch info & current commit sha.
      id: get_branch
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: DOCKER | Login to Public Amazon ECR
      id: login-public-ecr
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ inputs.aws_mainnet_access_key_id }}
        password: ${{ inputs.aws_mainnet_secret_access_key }}
      env:
        AWS_REGION: us-east-1

    - name: FEATURENET ADDRESSES | Configure AWS credentials
      if: ${{ inputs.download_featurenet_addresses == 'true' }}
      uses: aws-actions/configure-aws-credentials@v1
      env:
        AWS_REGION: us-east-1
      with:
        aws-access-key-id: ${{ inputs.aws_devnet_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_devnet_secret_access_key }}
        aws-region: ${{ env.AWS_REGION }}

    - name: FEATURENET ADDRESSES | Copy addresses.json files from S3 bucket
      if: ${{ inputs.download_featurenet_addresses == 'true' }}
      shell: bash
      env:
        METADATA_PATH: src/addresses
        S3BUCKET_URL: s3://${{ inputs.ci_s3bucket_name }}/contracts/fe-benjamin-button
      run: |
        mkdir -p ${{ env.METADATA_PATH }}
        aws s3 cp ${{ env.S3BUCKET_URL }}/addresses.json ${{ env.METADATA_PATH }}/addresses.json
        aws s3 cp ${{ env.S3BUCKET_URL }}/commit_sha.txt ${{ env.METADATA_PATH}}/commit_sha.txt

    - name: DOCKER | Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: DOCKER | Build and push latest docker image
      id: build-image
      uses: docker/build-push-action@v2
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: ./Dockerfile
        push: true
        tags: public.ecr.aws/p6e8q1z1/${{ inputs.registry }}:${{ steps.get_branch.outputs.sha_short }}
        target: ${{ inputs.target }}

    - name: OUTPUTS | Set outputs with docker images
      id: outputs
      shell: bash
      run: |
        echo "::set-output name=image::public.ecr.aws/p6e8q1z1/${{ inputs.registry }}:${{ steps.get_branch.outputs.sha_short }}"
