name: Build and push docker image

inputs:
  registry:
    description: Registry name, either squid-processor or squid-api
    required: true
  target:
    description: --target argument for docker build command
    required: true
  aws_mainnet_access_key_id:
    required: true
  aws_mainnet_secret_access_key:
    required: true
  aws_devnet_access_key_id:
    required: true
  aws_devnet_secret_access_key:
    required: true

outputs:
  image_tag:
    description: Tag of the pushed image
    value: ${{ steps.outputs.outputs.image_tag }}

runs:
  using: composite
  steps:
    - name: Check if registry input is valid
      if: ${{ inputs.registry != 'squid-processor' && inputs.registry != 'squid-api' }}
      shell: bash
      run: |
        echo "Invalid registry input"
        exit 1

    - name: GIT | Get branch info & current commit sha.
      id: get_branch
      shell: bash
      run: |
        echo "branch=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: DOCKER | Login to Public Amazon ECR
      id: login-public-ecr
      uses: docker/login-action@v2
      with:
        registry: public.ecr.aws
        username: ${{ inputs.aws_mainnet_access_key_id }}
        password: ${{ inputs.aws_mainnet_secret_access_key }}
      env:
        AWS_REGION: us-east-1

    - name: DOCKER | Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master

    - name: DOCKER | Build and push latest docker image
      id: build-image
      uses: docker/build-push-action@v3
      with:
        context: .
        builder: ${{ steps.buildx.outputs.name }}
        file: ./Dockerfile
        push: true
        tags: public.ecr.aws/p6e8q1z1/${{ inputs.registry }}:${{ steps.get_branch.outputs.sha_short }}
        target: ${{ inputs.target }}

    - name: OUTPUTS | Set outputs with docker images
      id: outputs
      shell: bash
      run: |
        echo "image_tag=${{ steps.get_branch.outputs.sha_short }}" >> $GITHUB_OUTPUT
