name: Build and deploy

on:
  workflow_dispatch:
    inputs:
      buildImages:
        description: 'Build and push docker images'
        required: false
        type: boolean
        default: true
      deployImages:
        description: 'Deploy images'
        required: false
        type: boolean
        default: true
      buildFEBenjaminImages:
        description: 'Build docker images with metadata for fe-benjamin'
        required: false
        type: boolean
        default: true
      deployFEBenjaminImages:
        description: 'Deploy docker images with metadata for fe-benjamin instead of original ones'
        required: false
        type: boolean
        default: true

  push:
    paths-ignore:
      - '*.md'
    branches:
      - main
      - A0-1459-modify-workflow-to-push-the-image

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build_and_deploy_processor:
    runs-on: ubuntu-20.04
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v2

      - name: Build and push squid-processor image
        if: ${{ github.event != 'workflow_dispatch' || inputs.buildImages }}
        uses: ./.github/actions/build-and-push
        with:
          registry: squid-processor
          target: processor
          build_fe_image: ${{ (github.event != 'workflow_dispatch' || inputs.buildFEBenjaminImages) && 'true' || 'false' }}

  build_and_deploy_api:
    runs-on: ubuntu-20.04
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v2

      - name: Build and push squid-api image
        if: ${{ github.event != 'workflow_dispatch' || inputs.buildImages }}
        uses: ./.github/actions/build-and-push
        with:
          registry: squid-api
          target: query-node
          build_fe_image: ${{ (github.event != 'workflow_dispatch' || inputs.buildFEBenjaminImages) && 'true' || 'false' }}
