name: Build and deploy

on:
  pull_request:
    branches:
      - '**'
  push:
    paths-ignore:
      - '*.md'
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  build_and_deploy_processor:
    runs-on: ubuntu-latest
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v2
      - name: DOCKER | Build processor
        run: |
          docker build . --target processor -t public.ecr.aws/p6e8q1z1/squid-processor:$(git rev-parse --short HEAD)

  build_and_deploy_api:
    runs-on: ubuntu-latest
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v2
      - name: DOCKER | Build API
        run: |
          docker build . --target query-node -t public.ecr.aws/p6e8q1z1/squid-api:$(git rev-parse --short HEAD)
