name: Build and deploy

on:
  workflow_dispatch:
    inputs:
      buildImages:
        description: 'Build and push docker images'
        required: false
        type: boolean
        default: true
      deployImages:
        description: 'Deploy images'
        required: false
        type: boolean
        default: true
      buildFEBenjaminImages:
        description: 'Build docker images with metadata for fe-benjamin'
        required: false
        type: boolean
        default: true
      deployFEBenjaminImages:
        description: 'Deploy docker images with metadata for fe-benjamin instead of original ones'
        required: false
        type: boolean
        default: true

  push:
    paths-ignore:
      - '*.md'
    branches:
      - main
      - A0-1459-modify-workflow-to-push-the-image

jobs:
  build_and_push_processor:
    name: Build and push Processor
    if: ${{ github.event != 'workflow_dispatch' || inputs.buildImages }}
    runs-on: ubuntu-20.04
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v2

      - name: DOCKER | Build and push squid-processor image
        uses: ./.github/actions/build-and-push
        with:
          registry: squid-processor
          target: processor
          build_fe_benjamin_image: ${{ (github.event != 'workflow_dispatch' || inputs.buildFEBenjaminImages) && 'true' || 'false' }}
          aws_mainnet_access_key_id: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
          aws_mainnet_secret_access_key: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}
          aws_devnet_access_key_id: ${{ secrets.AWS_DEVNET_ACCESS_KEY_ID }}
          aws_devnet_secret_access_key: ${{ secrets.AWS_DEVNET_SECRET_ACCESS_KEY }}
          ci_s3bucket_name: ${{ secrets.CI_S3BUCKET_NAME }}

  build_and_push_api:
    name: Build and push API
    if: ${{ github.event != 'workflow_dispatch' || inputs.buildImages }}
    runs-on: ubuntu-20.04
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v2

      - name: DOCKER | Build and push squid-api image
        uses: ./.github/actions/build-and-push
        with:
          registry: squid-api
          target: query-node
          build_fe_benjamin_image: ${{ (github.event != 'workflow_dispatch' || inputs.buildFEBenjaminImages) && 'true' || 'false' }}
          aws_mainnet_access_key_id: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
          aws_mainnet_secret_access_key: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}
          aws_devnet_access_key_id: ${{ secrets.AWS_DEVNET_ACCESS_KEY_ID }}
          aws_devnet_secret_access_key: ${{ secrets.AWS_DEVNET_SECRET_ACCESS_KEY }}
          ci_s3bucket_name: ${{ secrets.CI_S3BUCKET_NAME }}

  deploy_processor:
    name: Deploy Processor
    if: ${{ (always() && (needs.build_and_push_processor.result == 'success' || needs.build_and_push_processor.result == 'skipped')) && (github.event != 'workflow_dispatch' || inputs.deployImages) }}
    needs: build_and_push_processor
    runs-on: ubuntu-20.04
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v2

      - name: DEVNET | Deploy squid-process image to devnet
        uses: ./.github/actions/deploy
        with:
          registry: squid-processor
          deploy_fe_benjamin_image: ${{ (github.event != 'workflow_dispatch' || inputs.deployFEBenjaminImages) && 'true' || 'false' }}
          aws_devnet_access_key_id: ${{ secrets.AWS_DEVNET_ACCESS_KEY_ID }}
          aws_devnet_secret_access_key: ${{ secrets.AWS_DEVNET_SECRET_ACCESS_KEY }}
          github_token: ${{ secrets.CI_GH_TOKEN }}
          ci_s3bucket_name: ${{ secrets.CI_S3BUCKET_NAME }}
  
  deploy_api:
    name: Deploy API
    if: ${{ (always() && (needs.build_and_push_api.result == 'success' || needs.build_and_push_api.result == 'skipped') && (needs.deploy_processor.result == 'success' || needs.deploy_processor.result == 'skipped')) && (github.event != 'workflow_dispatch' || inputs.deployImages) }}
    needs: [build_and_push_api, deploy_processor]
    runs-on: ubuntu-20.04
    steps:
      - name: GIT | Checkout
        uses: actions/checkout@v2

      - name: DEVNET | Deploy squid-api image to devnet
        uses: ./.github/actions/deploy
        with:
          registry: squid-api
          deploy_fe_benjamin_image: ${{ (github.event != 'workflow_dispatch' || inputs.deployFEBenjaminImages) && 'true' || 'false' }}
          aws_devnet_access_key_id: ${{ secrets.AWS_DEVNET_ACCESS_KEY_ID }}
          aws_devnet_secret_access_key: ${{ secrets.AWS_DEVNET_SECRET_ACCESS_KEY }}
          github_token: ${{ secrets.CI_GH_TOKEN }}
          ci_s3bucket_name: ${{ secrets.CI_S3BUCKET_NAME }}
